@baseUrl = http://127.0.0.1:8000


GET {{baseUrl}}/


GET {{baseUrl}}/rooms

### Guests
GET {{baseUrl}}/guests

### Bookings
GET {{baseUrl}}/bookings

### IP in JSON
GET {{baseUrl}}/api/ip

### Frontend page
GET {{baseUrl}}/rooms-page
